import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar.jsx";
import { Providers } from "./Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Providers> {children}</Providers>

        <Footer />
      </body>
    </html>
  );
}
